# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52643587f5219baead962f3577960ffbb495bf48135e4dc8b743675c611cf3dbd2b4792f3c6bd5344317578e590aacc8c883d017178c9d83b7added29844d9d1

test:
  secret_key_base: d364ff7b2b59217678e3825e6e640e1f8d5c5b21e09f6187d0055c7a80ebd6d0c6a6772fd1c00086858206d11f7be4917433477a788eacb030f15b1555fa300a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
